### ISSUE TITLE
Deprecation warning on PropTypes

### ISSUE THREAD

**Issue by skinofstars** [Vincent-P/react-marked-markdown#54]
Using with current React shows a deprecation warning

`
Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
`

**Comment by Vincent-P** [comment]
It should be fixed with #55.

**Comment by sungwoncho** [comment]
@Vincent-P could you do a release?
